#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <string.h>
#include <sys/types.h>
#include <sys/socket.h>
#include <sys/ioctl.h>
#include <netinet/in.h>
#include <netinet/ether.h>
#include <arpa/inet.h>
#include <errno.h>
#include <net/if.h>

char* get_ifname_for_ip(int sock, struct in_addr ipaddr) {
    struct ifreq  ifr;
        in_addr_t     addr, netmask;
            int           i;
                char         *ifname;

                    for(i = 0; i < 255; i++) {
                            memset(&ifr, 0, sizeof(ifr));
                                    ifr.ifr_ifindex = i;
                                            if(ioctl(sock, SIOCGIFNAME, &ifr) == -1) {
                                                        continue;
                                                                }

                                                                        if(ioctl(sock, SIOCGIFFLAGS, &ifr) == -1) {
                                                                                    fprintf(stderr, "ioctl(SIOCGIFFLAGS) for interface \"%s\" failed (%d): %s\n", 
                                                                                                        ifr.ifr_name, errno, strerror(errno));
                                                                                                                    continue;
                                                                                                                            }
                                                                                                                                    if(!(ifr.ifr_flags & IFF_UP)) {
                                                                                                                                                continue;
                                                                                                                                                        }

                                                                                                                                                                if(ioctl(sock, SIOCGIFADDR, &ifr) == -1) {
                                                                                                                                                                            fprintf(stderr, "ioctl(SIOCGIFADDR) for interface \"%s\" failed (%d): %s\n", 
                                                                                                                                                                                                ifr.ifr_name, errno, strerror(errno));
                                                                                                                                                                                                            continue;
                                                                                                                                                                                                                    }
                                                                                                                                                                                                                            if(((struct sockaddr_in*)&ifr.ifr_addr)->sin_family != AF_INET) {
                                                                                                                                                                                                                                        continue;
                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                        addr = ((struct sockaddr_in*)&ifr.ifr_addr)->sin_addr.s_addr;

                                                                                                                                                                                                                                                                if(ioctl(sock, SIOCGIFNETMASK, &ifr) == -1) {
                                                                                                                                                                                                                                                                            fprintf(stderr, "ioctl(SIOCGIFNETMASK) for interface \"%s\" failed (%d): %s\n", 
                                                                                                                                                                                                                                                                                                ifr.ifr_name, errno, strerror(errno));
                                                                                                                                                                                                                                                                                                            continue;
                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                            netmask = ((struct sockaddr_in*)&ifr.ifr_netmask)->sin_addr.s_addr;
                                                                                                                                                                                                                                                                                                                                    /* printf(stderr, "ifindex=%d name=%s netmask=%s\n", i, ifr.ifr_name, inet_ntoa(((struct sockaddr_in*)&ifr.ifr_netmask)->sin_addr)); */

                                                                                                                                                                                                                                                                                                                                            if((ipaddr.s_addr & netmask) == (addr & netmask)) {
                                                                                                                                                                                                                                                                                                                                                        ifname = (char*)malloc(strlen(ifr.ifr_name)+1);
                                                                                                                                                                                                                                                                                                                                                                    strcpy(ifname, ifr.ifr_name);
                                                                                                                                                                                                                                                                                                                                                                                return ifname;
                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                return NULL;
                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                sa_family_t iface_encap(int sock, const char *ifname) {
                                                                                                                                                                                                                                                                                                                                                                                                    struct ifreq  ifr;

                                                                                                                                                                                                                                                                                                                                                                                                        memset(&ifr, 0, sizeof(ifr));
                                                                                                                                                                                                                                                                                                                                                                                                            strcpy(ifr.ifr_name, ifname);

                                                                                                                                                                                                                                                                                                                                                                                                                if(ioctl(sock, SIOCGIFHWADDR, &ifr) == -1) {
                                                                                                                                                                                                                                                                                                                                                                                                                        fprintf(stderr, "ioctl(SIOCGIFHWADDR) for interface \"%s\" failed (%d): %s\n", 
                                                                                                                                                                                                                                                                                                                                                                                                                                        ifname, errno, strerror(errno));
                                                                                                                                                                                                                                                                                                                                                                                                                                                return -1;
                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                        return ifr.ifr_hwaddr.sa_family;
                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                        int main(int argc, char *argv[]) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                            struct arpreq       ar;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                int                 sock;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    struct sockaddr_in *saip;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        char               *ifname;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            unsigned char       ether[8];

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if(argc != 2) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        fprintf(stderr, "Usage: %s <ip_address>\n", argv[0]);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return 1;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        memset(&ar, 0, sizeof(ar));

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            saip = (struct sockaddr_in*)&ar.arp_pa;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if(!inet_aton(argv[1], &saip->sin_addr)) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        fprintf(stderr, "Invalid IP address \"%s\"\n", argv[1]);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return 1;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        sock = socket(PF_INET, SOCK_DGRAM, 0);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if(sock == -1) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    perror("socket");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return 1;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ifname = get_ifname_for_ip(sock, saip->sin_addr);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if(ifname == NULL) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                fprintf(stderr, "%s is not on a local network.\n", inet_ntoa(saip->sin_addr));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return 1;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if(iface_encap(sock, ifname) != ARPHRD_ETHER) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        fprintf(stderr, "Interface %s is does not use ethernet.\n", ifname);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return 1;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        saip->sin_family = AF_INET;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            strcpy(ar.arp_dev, ifname);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if(ioctl(sock, SIOCGARP, &ar) == -1) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if(errno == ENXIO) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    fprintf(stderr, "No ARP entry.  Sending packet...\n");

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                saip->sin_port = htons(7);  /* port doesn't matter.  7 = echo */
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if(sendto(sock, "Hi", 2, 0, &ar.arp_pa, sizeof(struct sockaddr_in)) == -1) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            perror("sendto");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return 1;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    /* give it a second to respond to an ARP request */
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                sleep(1);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if(ioctl(sock, SIOCGARP, &ar) == -1) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if(errno == ENXIO) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                fprintf(stderr, "Still no ARP entry.\n"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "The machine may be unreachable or just slow to respond.\n");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                perror("ioctl(SIOCGARP)");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return 1;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        perror("ioctl(SIOCGARP)");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return 1;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if(!(ar.arp_flags & ATF_COM)) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            fprintf(stderr, "ARP lookup incomplete.\n"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "The address may be unreachable or just slow to respond.\n");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return 1;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if(ar.arp_ha.sa_family != ARPHRD_ETHER) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    fprintf(stderr, "Unrecognized hardware address type: %hu\n", ar.arp_ha.sa_family);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return 1;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    /* printf("%s\n", ether_ntoa((struct ether_addr*)&ar.arp_ha.sa_data)); */
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        memcpy(ether, &ar.arp_ha.sa_data, 6);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            printf("%X:%X:%X:%X:%X:%X\n", (unsigned int)ether[0],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              (unsigned int)ether[1],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                (unsigned int)ether[2],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  (unsigned int)ether[3],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    (unsigned int)ether[4],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      (unsigned int)ether[5] );

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          return 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }

