/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JavaTest */

#ifndef _Included_JavaTest
#define _Included_JavaTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JavaTest
 * Method:    addOne
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_JavaTest_addOne
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
